#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

# NVIDIA
export LIBVA_DRIVER_NAME=nvidia-dkms
export XDG_SESSION_TYPE=wayland
export GMB_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia

# Wayland
export WLR_NO_HARDWARE_CURSORS=1

# zsh
export ZDOTDIR=$HOME/.config/zsh

# Steam
export SDL_VIDEODRIVER=wayland

exec Hyprland

