#!/usr/bin/env bash

toggle() {
  status=$(rfkill -J | jaq -r '.rfkilldevices[] | select(.type == "bluetooth") | .soft' | head -1)

  if [ "$status" = "unblocked" ]; then
    rfkill block bluetooth
  else
    rfkill unblock bluetooth
  fi
}

if [ "$1" = "toggle" ]; then
  toggle
else
  while true; do
    powered=$(bluetoothctl show | rg Powered | cut -f 2- -d ' ')

    # only works for a single connected device
    mac=`bluetoothctl devices | awk '{print $2}'`
    status=$(bluetoothctl info $mac)
    name=$(echo "$status" | rg Name | cut -f 2- -d ' ')

    if [[ "$(echo "$status" | rg Percentage)" != "" ]]; then
      mac=`echo $mac | sed 's/:/_/g'`
      battery="$(upower -i /org/freedesktop/UPower/devices/mouse_dev_"$mac" | rg percentage | awk '{print $2}' | cut -f 1 -d '%')%"
    else
      battery=""
    fi

    if [ "$powered" = "yes" ]; then
      if [ "$status" != "Missing device address argument" ]; then
        text="$name"
        icon=""
        color="#89b4fa"
        class="bt-connected"
      else
        icon=""
        text="Disconnected"
        color="#45475a"
        class=""
      fi
    else
      icon="󰂲"
      text="Bluetooth off"
      color="#45475a"
      class=""
    fi

    echo '{ "icon": "'"$icon"'", "battery": "'"$battery"'", "text": "'"$text"'", "color": "'"$color"'", "class": "'"$class"'" }'

    sleep 3
  done
fi
