#!/usr/bin/env bash

volicons=("" "󰕾" "")

vol() {
  pamixer --get-volume
}
ismuted() {
  pamixer --get-mute
  echo $?
}

setvol() {
  pamixer --set-volume $1
}

setmute() {
  pamixer -t
}

if [ "$1" = "mute" ]; then
  setmute
elif [ "$1" = "setvol" ]; then
  if [ "$2" -lt 1 ] || [ "$2" -gt 100 ]; then
    echo "Volume must be between 1 and 100"; exit 1
  fi
  setvol "$2"
else
  # initial values
  lvl=$(awk -v n="$(vol)" 'BEGIN{print int(n/34)}')
  ismuted=$(ismuted)

  if [ "$ismuted" = "false" ]; then
  	icon="${volicons[$lvl]}"
  else
    icon="󰖁"
  fi
  echo '{ "icon": "'"$icon"'", "percent": "'"$(vol)"'", "microphone": "'"$(vol "SOURCE")"'" }'

  # event loop
  pactl subscribe | rg --line-buffered "change" | while read -r _; do
    lvl=$(awk -v n="$(vol)" 'BEGIN{print int(n/34)}')
    echo $lvl
    ismuted=$(ismuted)

    if [ "$ismuted" = "false" ]; then
    	icon="${volicons[$lvl]}"
    else
      icon="󰖁"
    fi
    echo '{ "icon": "'"$icon"'", "percent": "'"$(vol)"'", "microphone": "'"$(vol)"'" }'
  done
fi
